### ISSUE TITLE
allow developer that calls attobot to close PR

### ISSUE THREAD

**Issue by JeffreySarnoff** [attobot/attobot#11]
I had learned that the appropriate way to re-check a new tag after some minor correction was to close and then reopen the pr.  It would help if my use of attobot <the only thing about github processing that is ok> did not preclude that close and reopen action, or something with the same outcome.

**Comment by simonbyrne** [comment]
I'm not sure what you mean, can you give an example or point to a PR where you had a problem?

**Comment by JeffreySarnoff** [comment]
I had tagged as a new release [ReadableNumbers.jl (v0.0.1)](https://github.com/JuliaArbTypes/ReadableNumbers.jl/tree/v0.0.1).  This is the (now closed) [PR](https://github.com/JuliaLang/METADATA.jl/pull/7384).  There was an appropriate suggestion to protect "Base.parse", and I made the changes.  At this point, I wanted github to update my PR for v0.0.1 with those few changes, and then re-check it and then allow the revised v0.0.1 to be registered and made available to others by Pkg.add("ReadableNumbers").  In the past, there has been guidance that closing the PR and then reopening the PR forces re-checking with the new changes incorporated [I may be missing a step].  When I use attobot to proffer the PR, then I do not have the authority to close that PR.  So I (thought it necessary) to create a new, later tag and PR at that tag for a hop-over v0.0.1 release.

**Comment by simonbyrne** [comment]
There is no need to close the PR to update it. Where did you see this?

In fact closing causes bigger problems, namely that it won't then let you
reopen it as github sees the update as a force push.

**Comment by JeffreySarnoff** [comment]
What should one do to have attobot incorporate some new file alterations into a currently requested PR?

**Comment by simonbyrne** [comment]
Delete the release and tag from your repo (see instructions in the attobot rearm), then create another release with the same version number. Attobot should then update the PR and make a comment to that effect.

**Comment by JeffreySarnoff** [comment]
thx

**Comment by tkelman** [comment]
The "close then reopen" recommendation is about restarting Travis if it fails initially but can be made to pass by some external change outside of a PR.
