### ISSUE TITLE
I'm getting random attobot issues in a repo that it should just leave alone

### ISSUE THREAD

**Issue by davidanthoff** [attobot/attobot#12]
E.g. JuliaEditorSupport/julia-vscode#137 and JuliaEditorSupport/julia-vscode#136.

Why is it even monitoring that repo?

**Comment by davidanthoff** [comment]
@simonbyrne It looks like you installed attobot for the whole JuliaEditorSupport organization and all repos in it. That doesn't make sense, there are a number of repos in that organization that should be left alone by attobot. Can you please undo that in some way, or just scope it to specific repos?

**Comment by simonbyrne** [comment]
I didn't enable it (it can only be done by people with admin access to the relevant org). Who is in charge of it?

**Comment by simonbyrne** [comment]
But to answer your question, it can be enabled only for specific repos, but it needs to be done by someone with admin rights to the org.

**Comment by simonbyrne** [comment]
@carlobaldassi are you an admin for the JuliaEditorSupport org?

**Comment by davidanthoff** [comment]
I'm an admin, so I'll just uninstall it for now.

**Comment by simonbyrne** [comment]
For future reference (or if you want to reenable it for specific repos)

1. Go to https://github.com/integration/attobot
2. Click on configure
3. Click on the org
4. Choose "Only select repositories"
5. Add the name of the repository, and click Save

**Comment by tkelman** [comment]
I think I blanket enabled it for every org I could, sorry. Attobot should ignore anything that doesn't look like a Julia package.
