### ISSUE TITLE
Show AppVeyor Test Tags

### ISSUE THREAD

**Issue by ChrisRackauckas** [attobot/attobot#13]
There's no reason to not care about Windows. It should at least be highlighted during the release process that a package's tests fail or don't fail on Windows in the same way that it is for other OSs.

**Comment by simonbyrne** [comment]
I assure you it's not for a lack of caring, but that Appveyor doesn't yet provide a way to get the badge & link of a build of a specific tag or commit. 

c.f. https://github.com/appveyor/ci/issues/1205

**Comment by ChrisRackauckas** [comment]
I guess that intro came off as stronger than I wanted it to. What about putting the badge for AppVeyor on master for the time being?

**Comment by simonbyrne** [comment]
Haha, no worries.

That might be a reasonable interim measure.

**Comment by simonbyrne** [comment]
Ah, the other issue is that there's no great way to get a link to the Appveyor results. The best option that I can think of at the moment is scraping the repository README.

**Comment by simonbyrne** [comment]
Closed in favour of [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)
