### ISSUE TITLE
Ignore repos that don't look at all like julia packages

### ISSUE THREAD

**Issue by tkelman** [attobot/attobot#14]
To avoid nuisance issues on tags of repos that get attobot enabled by accident, like from being in an organization with a lazy admin who clicks "enable on all repos."

**Comment by simonbyrne** [comment]
Probably not a bad idea. What criteria do you suggest for determining whether or not a repo is a Julia package?

**Comment by tkelman** [comment]
Is there a `src/PackageName.jl` file that matches the repo name

**Comment by simonbyrne** [comment]
The only downside I can see is if the user has renamed the repository but forgotten the file rename, they won't have any idea why it fails.

**Comment by tkelman** [comment]
Is there a github API for language stats? We could compare several indicators - existence of the module file, language stats, existence of any .jl files in src, etc. If none of them make it look like a Julia package then it would be fairly safe to assume it isn't.

**Comment by simonbyrne** [comment]
Ah, there is, e.g.:
https://api.github.com/repos/JuliaLang/julia/languages

For reference, here is what repo from #12 gives:
https://api.github.com/repos/JuliaEditorSupport/julia-vscode/languages

**Comment by iamed2** [comment]
This is going to come up more with [BinaryBuilder repos](https://github.com/staticfloat/NettleBuilder) which contain a Julia script but aren't packages.

We have attobot enabled org-wide so less-privileged users can make and register a new Julia package without requiring admin intervention.

**Comment by simonbyrne** [comment]
Yeah, what do you suggest? I think we should just base it on whether it has a ".jl" suffix. The only problem is that users won't have a way to warn them

**Comment by iamed2** [comment]
If they ask about it, it will be immediately obvious though. 

> newuser: Why doesn't my package work with attobot? https://github.com/newuser/NewPkg
> expert: ah, the repo needs to have a .jl suffix

**Comment by simonbyrne** [comment]
And in case anyone is wondering, we can't just open an issue once. This is part of the problem with AttoBot's stateless design
