### ISSUE TITLE
Verify that Travis runs against all supported Julia versions

### ISSUE THREAD

**Issue by tkelman** [attobot/attobot#15]
I currently have to check this manually, but it would be neat if possible to do here. Parse the .travis.yml, if present, and compare to REQUIRE. If a package still says it supports 0.4, then its travis, if running, should be sure to test against it.

**Comment by simonbyrne** [comment]
would this be better handled by the METADATA CI?

**Comment by tkelman** [comment]
Not all packages can run on Travis though, so it shouldn't be a failure, more of a warning. We don't have a great mechanism for having the METADATA Travis check return anything other than success or failure (most people won't look at the logs if we put non-fatal warning messages there).

This kind of check would seems to fit in fairly well with the Travis badge that attobot adds to the PR description.

**Comment by simonbyrne** [comment]
Closed in favour of [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)
