### ISSUE TITLE
No PR for DynamicalBilliards.jl

### ISSUE THREAD

**Issue by Datseris** [attobot/attobot#16]
I installed Attobot in order to avoid the complications of PkgDev. 

The tutorial says I should open an issue if there is not anything done within some seconds and there has passed several minutes since then. I haven;t gotten any notification on my email, so I checked the PRs at the official METADATA.jl page. I also did not find anything there.

I have had many release versions tagged on github before installing Attobot. After installing attobot I made a new minor tag release, i.e. from v0.5.0 to v0.5.1 .

Let me know what else information I should give you.

**Comment by simonbyrne** [comment]
It seems to have worked fine: https://github.com/JuliaLang/METADATA.jl/pull/7678

Not sure why you didn't see it or weren't notified. Perhaps some problem with GitHub.

**Comment by Datseris** [comment]
I just saw it. I will check again the github settings, maybe give then a different address. 
Also, I am sorry I did not see that it worked fine. I am a noob and I pressed on the "Commits" links on metadata instead of the Pull Requests page.

**Comment by simonbyrne** [comment]
No problem.
