### ISSUE TITLE
Delete branch from attobot METADATA fork when PR closed or merged

### ISSUE THREAD

**Issue by tkelman** [attobot/attobot#17]
I think you have this planned as a way of solving #6, making it so people can close their PR's if they want without hitting that github force push issue. It's also a big mess to look at the "which branches is this commit in" indicator on anything from attobot's fork, e.g. https://github.com/attobot/METADATA.jl/commit/a8977a09e7c3c5fbd588c1c795bfa15c2caf8fc2

**Comment by simonbyrne** [comment]
This should hopefully be working now.

**Comment by tkelman** [comment]
confirmed https://github.com/JuliaLang/METADATA.jl/pull/7760

**Comment by tkelman** [comment]
Would it be possible to have like a 5-minute delay on this? When Travis doesn't trigger for whatever reason, close-and-reopen is usually the easiest fix. But if attobot immediately deletes the branch then that requires re-submitting the release in a new PR now.

**Comment by simonbyrne** [comment]
Possibly. The easiest way would be to just insert a sleep in the lambda function, then check if the PR has been reopened? The two constraints are:
- AWS lambda functions can only be 300 seconds (5 minutes). Also, I'm paying for the time the function is sleeping (granted, this isn't a lot, but still)
- GitHub expects a response within 30 seconds. I don't think it really matters, but it does make debugging easier.

How about I start with a delay of 20 seconds, and see how that goes? If you decide that it would be useful to be longer we can reevaluate.

**Comment by tkelman** [comment]
Oh, I thought you were running in a free tier. Can we get this paid for on an organizational account then?

Travis failing to trigger is reasonably uncommon, not sure if 20 seconds would be enough but we could try it. One option other than sleeping within the job is having the lambda job trigger a scheduled future job, if that's possible?

**Comment by simonbyrne** [comment]
Actually, I think it might still be in the free tier: it's the logging to S3 that costs a few cents per month.

I've set the 20 second delay: let me know how it goes (I haven't tested it yet). There probably is some way to get it to trigger a future job (or, say, add it to a queue for a nightly run), but that would require quite a few changes.
