### ISSUE TITLE
Make the person who created the tag the commit author

### ISSUE THREAD

**Issue by Keno** [attobot/attobot#18]
We may not have this info, but it would be nice if the commit author was set to the person creating the tag, rather than attobot itself.

**Comment by simonbyrne** [comment]
That's a good idea, however I'm not sure it is possible. In order [to create a commit in the name of another user](https://developer.github.com/v3/git/commits/#optional-parameters) you need their name and email, but [users are not required to have a public email](https://developer.github.com/v3/users/#get-a-single-user).

**Comment by simonbyrne** [comment]
Also, I can't fetch it from the tag (as opposed to the release) as GitHub releases creates lightweight tags, which don't have author info. Grr.

**Comment by MikeInnes** [comment]
Just use the commit author when the info is available? Sometimes github uses `username@users.noreply.github.com` or similar when there's no public email, so we could use that as a standin.

**Comment by simonbyrne** [comment]
That's a good idea.

**Comment by simonbyrne** [comment]
Hmm, the corresponding commits look a bit funny:
https://github.com/JuliaLang/METADATA.jl/pull/9303/commits/ef973c3b2f298809d97f46b213e0e1ac4dc3738a
Maybe they special-case the `users.noreply.github.com` addresses somehow?

(here is the corresponding commit via the api https://api.github.com/repos/JuliaLang/METADATA.jl/git/commits/ef973c3b2f298809d97f46b213e0e1ac4dc3738a)

**Comment by MikeInnes** [comment]
You probably have to have the private email option explicitly enabled for github to link it to your account.

It may make sense to just use AttoBot for the github when there's no public email.

**Comment by simonbyrne** [comment]
From GitHub support:

> Users won't be credited when commits are authored with that email address unless they enable the "Keep my email address private" setting on their account. Could you check with those users and make sure they have that option enabled?

**Comment by simonbyrne** [comment]
Well, I've worked around it by getting it from the last commit by the author in that repo.
