### ISSUE TITLE
No PR opened

### ISSUE THREAD

**Issue by mlubin** [attobot/attobot#19]
I just enabled attobot on MathProgBase.jl and tagged [v0.6.0](https://github.com/JuliaOpt/MathProgBase.jl/releases/tag/v0.6.0). It's been a few minutes without a corresponding PR to METADATA.

Thanks!

**Comment by simonbyrne** [comment]
Ah, the problem is that there are some older versions which have `-dev` suffixes. I'll have to make some changes to the code.

**Comment by mlubin** [comment]
I can delete those tags if it would help, not sure why they were even made.

**Comment by simonbyrne** [comment]
No, it's not the tags, but the fact that they're in METADATA. I'll have to make some small changes, but probably won't get to it until tomorrow.

**Comment by simonbyrne** [comment]
Ah, you just beat me! Anyway, here it is:
https://github.com/JuliaLang/METADATA.jl/pull/7838

**Comment by mlubin** [comment]
Awesome, thanks!
