### ISSUE TITLE
Testing downstream packages upon the creation of a new tag

### ISSUE THREAD

**Issue by juliohm** [attobot/attobot#22]
As Julia evolves, many packages are built on top of each other and it becomes hard to release a new version with breaking changes. It would be helpful if we, as the authors of a package `MyPackage`, were able to see right away the impact of the breaking changes in downstream packages.

We can manually do this with:

```julia
downstream = Pkg.dependents("MyPackage")
for pkg in downstream
  Pkg.test(pkg)
end
```

but I wonder if we could have a built-in functionality in attobot for handling this breaking changes more seriously. Do you have suggestions on how that could be achieved?

cc: @tkelman, @sbromberger

**Comment by juliohm** [comment]
I am cc'ing again in a comment as I forgot to cc in the beginning (not sure if GitHub sends notifications when we update a comment)

cc: @tkelman, @sbromberger

**Comment by tkelman** [comment]
this isn't exactly practical within the constraints of AWS Lambda, where attobot runs. But we're working on something separate for this.

**Comment by simonbyrne** [comment]
Perhaps with Pkg3, but this would be better done at the METADATA level rather than as part of AttoBot.
