### ISSUE TITLE
Make Attobot compare against latest parent release instead of latest absolute release

### ISSUE THREAD

**Issue by Evizero** [attobot/attobot#24]
For example if there already exists a version `v0.1.0` of some package which is 0.6 only, and I want to tag a backport `v0.0.2`. Right now it would compare against `v0.1.0` instead of `v0.0.1`. 

see https://github.com/JuliaLang/METADATA.jl/pull/8724 for an example

Note that it works properly, it is just the PR message that is a bit unhelpful in such cases

**Comment by simonbyrne** [comment]
That seems reasonable.
