### ISSUE TITLE
New release did not create METADATA PR or issue (Iterators.jl)

### ISSUE THREAD

**Issue by iamed2** [attobot/attobot#26]
This release: https://github.com/JuliaCollections/Iterators.jl/releases/tag/v0.3.1
did not create a METADATA PR or issue on Iterators.jl.

**Comment by simonbyrne** [comment]
Thanks, I seem to have broken it. Will fix it soon.

**Comment by iamed2** [comment]
Popped up here, not sure if that was you just now: https://github.com/JuliaLang/METADATA.jl/pull/8988

**Comment by simonbyrne** [comment]
Yep, just fixed and retriggered it.

**Comment by iamed2** [comment]
Thanks!
