### ISSUE TITLE
trouble tagging Clp.jl 0.3.1

### ISSUE THREAD

**Issue by mlubin** [attobot/attobot#27]
Possibly doing something silly on my end, but I just tagged Clp.jl v0.3.1 and haven't seen a corresponding PR to METADATA. Any ideas?

Thanks!

**Comment by simonbyrne** [comment]
Fixed: https://github.com/JuliaLang/METADATA.jl/pull/8992

I broke attobot earlier, and in my testing broke the rate limit. I've enabled auth on all requests now, so it should be okay.
