### ISSUE TITLE
Tag reminders

### ISSUE THREAD

**Issue by musm** [attobot/attobot#28]
I'm not sure if this is in the realm of possibilities. But it would be interesting to see if it's possible to add reminders to tag a package for new commits that have been available on master for more than x days/months. This would help remind package authors to tag updates to their packages

**Comment by simonbyrne** [comment]
I like the idea, but might be better handled by [PackageEvaluator.jl](https://github.com/JuliaCI/PackageEvaluator.jl)?

**Comment by tkelman** [comment]
PackageEvaluator never touches master of anything, only releases from metadata

**Comment by simonbyrne** [comment]
But it could theoretically check if the master branch has had commits since the last tag?

**Comment by tkelman** [comment]
not all packages use master as their default branch, but that could be put in somewhere - it wouldn't really fit with the main testing loop though

**Comment by simonbyrne** [comment]
Closed in favour of [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)
