### ISSUE TITLE
Is attobot only triggered if the release is created as shown in the documentation?

### ISSUE THREAD

**Issue by dmbates** [attobot/attobot#3]
Instead of going back and reading the documentation for attobot before creating the v0.7.1 release of [`MixedModels`](https://github.com/dmbates/MixedModels.jl) I relied on my memory of how attobot works.

Turns out relying on my memoryy wasn't such a great idea. 

I used `PkgDev.tag("MixedModels")` in Julia to tag the package then used the `Tags` tab on the Github repository to create a release.  So Release v0.7.1 does indeed exist on the Github repository but it seems that it did not trigger attobot to create a pull request on the `METADATA` repository.

What would be a good way of triggering the PR on `METADATA`?

**Comment by simonbyrne** [comment]
It was triggered, but something failed. I'll look into it.

**Comment by simonbyrne** [comment]
Not sure what is going on here: when I query the API to try to find the head commit via:
https://api.github.com/repos/dmbates/MixedModels.jl/git/refs/tags/v0.7.1
I get:
```
{
  "ref": "refs/tags/v0.7.1",
  "url": "https://api.github.com/repos/dmbates/MixedModels.jl/git/refs/tags/v0.7.1",
  "object": {
    "sha": "3722270c5619a86a39890d4c4ceaf984807ac3af",
    "type": "tag",
    "url": "https://api.github.com/repos/dmbates/MixedModels.jl/git/tags/3722270c5619a86a39890d4c4ceaf984807ac3af"
  }
}
```
But that sha doesn't exist.

**Comment by simonbyrne** [comment]
The problem is the tag is pointing to another tag: I'm not quite sure how that happened, as the website is correct. I got in touch with GitHub, they're usually pretty quick to reply. Let's see what they say.

**Comment by dmbates** [comment]
I removed the v0.7.1 release and have now created a v0.7.2 release

**Comment by simonbyrne** [comment]
That works too, but I would like to know what happened there.

**Comment by simonbyrne** [comment]
I think I figured this out: `PkgDev.tag` creates an annotated tag instead of a lightweight tag, causing slightly different behaviour from the API. Anyway, it should be able to handle both now.
