### ISSUE TITLE
React to "tag deleted" event?

### ISSUE THREAD

**Issue by tkelman** [attobot/attobot#30]
Does github send events for that? If so it would be good to signal somehow "this PR is WIP, the submitter just deleted the release that triggered it, don't merge right this moment since the tag sha's might not match." Maybe re-trigger travis (eats a few minutes of queue for something that is likely to fail, not ideal), change the title to WIP until a new version of the release triggers an amended metadata PR commit, or add a "hold on, revision in progress" comment?

**Comment by simonbyrne** [comment]
Unfortunately not (or at least they didn't a couple of months ago). There is one for removing tags, but the user may not delete the tag at the same time.

**Comment by tkelman** [comment]
deleting the tag is the actual problematic one as far as metadata is concerned

**Comment by simonbyrne** [comment]
True. The other issue is that I can't change the permissions of an existing integration, it would require creating a whole new one (and getting people to switch over). 

If we're going to do that it would be worth thinking what other permissions would be useful.

**Comment by tkelman** [comment]
sounds not worth it just yet until we have a more compelling feature that warrants an "attobot 2" upgrade, but may as well do at the same time if we remember

**Comment by simonbyrne** [comment]
Closed in favour of [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)
