### ISSUE TITLE
`@ping` all repo watcher's in in the PR to METADATA

### ISSUE THREAD

**Issue by oxinabox** [attobot/attobot#33]
Right now when attobot makes a METADATA PR, it cc's the person who it is making the PR on behalf of.

I suggest it should all tag anyone who is currently Watching the package repo on github.
Because they have selected Watching, which indicates they want to be aware of every thing going on WRT a package.
Presumably, they also want to know when a release is proposed.

**Comment by MikeInnes** [comment]
Don't watchers get notified when a tag is made?

**Comment by oxinabox** [comment]
They don't get notified of any discussion that happens in the METADATA.jl  PR though.
and they don't get notified when that PR is Merged, and the release made official.
Knowing the status of that PR is what lets you know if a release has been made.

**Comment by simonbyrne** [comment]
I'm not opposed to the idea, but some people might find it annoying. A big package like Distributions.jl might end up pinging 40-odd people.

**Comment by tkelman** [comment]
I think "watching" results in a slightly different level of notification than being directly @-mentioned.

**Comment by oxinabox** [comment]
>I'm not opposed to the idea, but some people might find it annoying. A big package like Distributions.jl might end up pinging 40-odd people.

When you tick the "watching" box, you are signing up to be annoyed.
You get notifications for every new PR and Issue raised.
I think you also get notifications for every comment on every PR or Issue, but I am less sure of that.

For a big repo like  Distributions.jl between every release those 40 watchers are already getting at very least half a dozen notifications. 
And I assert that they want these notifications, it is why they decided to watch (I certainly do).

I would look at a PR to Metadata as equivalent to a PR or Issue on the repository,

**Comment by simonbyrne** [comment]
Having thought about it a bit more, I broadly agree with your point, though it would be nice if there was a way to do it without mentioning everybody on the issue (one idea is to open a corresponding issue on the repository itself, but that could get messy, as it just leads to 2 places for the same discussion).

I'll hold off for a week or two, as I'm travelling at the moment and won't have time to fix attobot when I inevitably break it. This will also give other people time to chime in.

**Comment by tkelman** [comment]
a list of 40 names in each pr would get pretty excessive

maybe with some named groups like `@attobot/Distributions-watchers`, if that's not too much trouble to have attobot auto update that kind of list

**Comment by dpo** [comment]
Bump. I think the OP's proposal is very desirable. At least, it could be an Attobot option. To avoid listing people individually, there may be a way to ping the organization.

**Comment by MikeInnes** [comment]
Or just open an issue on the original repo with a cross-ref, and close it when the tag is merged.

**Comment by oxinabox** [comment]
Though opening an issue on original repo does risk fragmenting discussion if there are issues with merging.

**Comment by simonbyrne** [comment]
Closed in favour of [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)
