### ISSUE TITLE
attobot is not tracking releases

### ISSUE THREAD

**Issue by TransGirlCodes** [attobot/attobot#35]
I'm in the process of releasing a Hotfix release for BioSequences.jl which will be version 0.6.2, and also doing a release for GeneticVariation.jl https://github.com/JuliaLang/METADATA.jl/pull/9921#issuecomment-310616681

Yesterday evening, when I tagged the BioSequences.jl v0.6.2 release I noticed that attobot did not create a PR, despite attobot being configured to watch those two packages.

Also, whilst attobot created a PR for GeneticVariation.jl, it has stopped updating it when I made changes to the release in response to comments.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/9942 seems to have worked, odd

**Comment by TransGirlCodes** [comment]
Perhaps I shall uninstall and reinstall attobot for the BioJulia org, and see what happens.

**Comment by TransGirlCodes** [comment]
Ok I don't know what the issue was, but uninstalling and re-installing attobot fixed this for me.

**Comment by simonbyrne** [comment]
It appears to have been an AWS Lambda outage. Let me know if anything is still missing and I can retrigger it manually.
