### ISSUE TITLE
delete attobot PR?

### ISSUE THREAD

**Issue by TsurHerman** [attobot/attobot#37]
I am a new user of attobot, I submitted several PR's publishing my new package until
I got the hang of CI , now I want to delete my initial failed attaempts.
How do I delete PR's that attobot already issued in my name?
I deleted the tag and release but the PR is still showing in METADATA repo.

Thanks.

**Comment by simonbyrne** [comment]
Unfortunately there isn't a way to do this. The best way at the moment is to leave a comment on the pull request that it should be closed.
