### ISSUE TITLE
upper bound bumped dependency in previous versions

### ISSUE THREAD

**Issue by shashi** [attobot/attobot#38]
When for example I bump the version of IndexedTables required by JuliaDB from 0.4.2 to 0.5.1, it would be nice if attobot goes through the `require` file of all the previously tagged versions of JuliaDB and puts an upper bound of 0.5.1 (exclusive) if an upper bound doesn't already exist.

**Comment by tkelman** [comment]
You don't want to do this unless there's a breaking change. It's fairly subtle to do this correctly.

**Comment by shashi** [comment]
Hi Tony, good to see you here!

Maybe this can be done via a comment on the PR then. "@attobot upperbound IndexedTables"

**Comment by simonbyrne** [comment]
attobot is basically in maintenance mode: this might be possible in [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl), so maybe open an issue there.
