### ISSUE TITLE
Where did I go wrong (take 2)?

### ISSUE THREAD

**Issue by cormullion** [attobot/attobot#4]
I swear I did it right this time (:)) but Attobot didn't pick it up:

https://github.com/cormullion/Luxor.jl/releases/tag/v0.7.0

Is there like a queue or log or something where you can check on progress? 

Attobot's cool so I want to get it working...

**Comment by simonbyrne** [comment]
It appears to be the same issue as #3. So I can understand what is happening, what steps did you do?

**Comment by cormullion** [comment]
I did PkgDev tag minor, git commit and push, git push tags, then went to make a new release on GitHub (rather than the tags tab).

**Comment by simonbyrne** [comment]
Okay, should be fixed now: I retriggered the PR here:
https://github.com/JuliaLang/METADATA.jl/pull/7279
