### ISSUE TITLE
Intervals.jl release not detected

### ISSUE THREAD

**Issue by rofinn** [attobot/attobot#42]
https://github.com/invenia/Intervals.jl/releases/tag/v0.0.7

NOTE: For now I've just manually updated [METADATA](https://github.com/JuliaLang/METADATA.jl/pull/14792)

**Comment by simonbyrne** [comment]
Hmm, no idea what happened: logs just say `{"message": "Internal server error"}`. I guess it was some sort of AWS gateway thing.

**Comment by simonbyrne** [comment]
(also, if you have trouble again, let me know and i can retrigger the process manually)
