### ISSUE TITLE
Fixing Bad Releases/Manual Trigger?

### ISSUE THREAD

**Issue by arnavs** [attobot/attobot#43]
I had a bad tag that wasn't semvar'd properly, so I updated the tag. But I don't think Attobot is still watching. It would be great if I could manually trigger attobot once the release is fixed.

for context: https://github.com/econtoolkit/Expectations.jl/releases

**Comment by simonbyrne** [comment]
Hmm: I think you may need to delete release and recreate it.

**Comment by arnavs** [comment]
Probably. But I think it’d be great to be able to @attobot or something, and have it work out what’s needed.

**Comment by simonbyrne** [comment]
attobot does need a bit of a revamp for Pkg3, so I'll try to think how we can make this easier.

**Comment by arnavs** [comment]
Perfect :)
