### ISSUE TITLE
No pull request for Hwloc.jl

### ISSUE THREAD

**Issue by eschnett** [attobot/attobot#47]
I tagged a new release for Hwloc yesterday <https://github.com/JuliaParallel/Hwloc.jl/releases/tag/v1.0.0>, and attobot should have opened a pull requeste for METADATA. It didn't. How do I proceed?

**Comment by simonbyrne** [comment]
Not sure what happened. I retriggered it and it worked: https://github.com/JuliaLang/METADATA.jl/pull/17206
