### ISSUE TITLE
REQUIRE file for Julia 1.0

### ISSUE THREAD

**Issue by 0** [attobot/attobot#48]
I've received [a complaint](https://github.com/0/Qutilities.jl/issues/1) from attobot: "Error tagging new release. The REQUIRE file could not be found." However, as far as I can tell, the Julia 1.0 [docs](https://docs.julialang.org/en/v1.0.0/) don't mention a `REQUIRE` file.

It was [mentioned](https://github.com/attobot/attobot/issues/43#issuecomment-407889369)  recently that "attobot does need a bit of a revamp for Pkg3", which is understandable. In the meantime, should I appease attobot by creating an empty `REQUIRE` file?

**Comment by simonbyrne** [comment]
Yes, but the REQUIRE file should match the dependencies in the Project.toml

**Comment by 0** [comment]
Thank you! That appears to have worked.
