### ISSUE TITLE
don't require REQUIRE

### ISSUE THREAD

**Issue by tpapp** [attobot/attobot#50]
It would be nice not to reject packages that don't have a `REQUIRE`, only a `Project.toml`. 

Packages that have transitioned to the new format have to maintain a `REQUIRE` just for `attobot`. Cf #48, [this discussion](https://discourse.julialang.org/t/attobot-for-pkg3-projects/13371)

**Comment by simonbyrne** [comment]
Yes, we're still trying to figure out how this might work.

**Comment by tpapp** [comment]
Friendly ping: is there a timeline for this?

**Comment by tpapp** [comment]
In the meantime, I wrote a script generating a REQUIRE automatically, as a workaround.

https://gist.github.com/tpapp/3b6def2b43cfb9566e3048c37aeed6ab

**Comment by simonbyrne** [comment]
fixed by using [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)
