### ISSUE TITLE
REQUIRE file

### ISSUE THREAD

**Issue by andreasdominik** [attobot/attobot#51]
Attobot complains about a missing REQUIRE file.
As I understood, the information is moved to Project.toml and manifest.toml and I assume the REQUIRE file is obsolete (because redundant).

If this is so, attobot should accept packages without REQUIRE.

Thank you for your help - attobot is great; it makes package maintenance easy as a walk in the park!
Cordially
Andreas

**Comment by simonbyrne** [comment]
Yes, it should. Still need to figure out how this will work.

Duplicate of #50.

**Comment by andreasdominik** [comment]
thank you for caring!
