### ISSUE TITLE
disable attobot for specific repo

### ISSUE THREAD

**Issue by tpapp** [attobot/attobot#52]
Is it possible not to trigger attobot in a repo when I make a release?

Without, of course, removing it globally and allowing it only for specific repos (ie all but a particular one).

The particular repo is https://github.com/tpapp/skeleton.jl, which is just a script, not a package.

**Comment by simonbyrne** [comment]
The easiest way at the moment is to remove the .jl suffix. I think in the next iteration we will change it to depend on the presence of a Project.toml file.

**Comment by simonbyrne** [comment]
attobot is basically in maintenance mode: please use [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)
