### ISSUE TITLE
no PR on metadata cc:ing me

### ISSUE THREAD

**Issue by yakir12** [attobot/attobot#54]
I registered attabot on https://github.com/yakir12/FFmpegPipe.jl and published a [release](https://github.com/yakir12/FFmpegPipe.jl/releases/tag/v1.0.1). Nothing has happened for 10 minutes now (sorry, it said to open an issue after 30 seconds or so). Maybe it has to do with https://github.com/yakir12/FFmpegPipe.jl being a fork of https://github.com/perrutquist/FFmpegPipe.jl ? If so, see [here](https://github.com/perrutquist/FFmpegPipe.jl/pull/3#issuecomment-428572672).

**Comment by simonbyrne** [comment]
The problem is that you don't have a REQUIRE file (see here https://github.com/attobot/attobot/issues/50). This usually would have triggered an issue on your repo, but because it is a fork, issues are disable by default.

**Comment by yakir12** [comment]
Oh I see. Sorry to ask here, but what should I do to publish a v1 package?
Add a mock yet correct REQUIRE file?

**Comment by simonbyrne** [comment]
Yes, basically.

**Comment by yakir12** [comment]
Thanks.
