### ISSUE TITLE
Attobot did not create a pull request

### ISSUE THREAD

**Issue by dcarrera** [attobot/attobot#55]
Hello,

The instructions for Attobot say that if I don't see a PR within 30 seconds I'm supposed to open an issue. The package in question is here: https://github.com/dcarrera/Planets.jl

I installed Attobot and then I made my first release. After several minutes I don't see any PR in https://github.com/JuliaLang/METADATA.jl/pulls

Please let me know if I've made a mistake somewhere.

**Comment by simonbyrne** [comment]
https://github.com/dcarrera/Planets.jl/issues/1

See #50.

**Comment by dcarrera** [comment]
Thanks. I just added a REQUIRE file and made a new release. Now I see the PR in METADATA.jl.
