### ISSUE TITLE
Did not generate a PR for new repo

### ISSUE THREAD

**Issue by tobydriscoll** [attobot/attobot#56]
I tagged [v0.1.0](https://github.com/tobydriscoll/HaltonSequences.jl/releases/tag/v0.1.0) of my package for a new contribution. I got no messages and see no new PR for it on METADATA after 13 minutes. 

(An earlier attempt with the tag name "0.1.0" did generate an issue complaining about the tag name.)

**Comment by simonbyrne** [comment]
No idea what happened, I don't see anything in the log (other than the "0.1.0" issue). Can you try deleting it and retagging again?

**Comment by tobydriscoll** [comment]
Looks like it went through this time. Maybe it's because I just renamed the tag from the release page, rather than creating a new release.

**Comment by simonbyrne** [comment]
ah, that's probably it. glad you figured it out.
