### ISSUE TITLE
Unable to detect ONNX release

### ISSUE THREAD

**Issue by ayush1999** [attobot/attobot#58]
I just updated FluxML/ONNX.jl to v0.1.0. Isn't attobot expected to make a PR for this in metadata.jl? Because there was no PR from attobot's side.

**Comment by simonbyrne** [comment]
I'm not sure what happened, looks like something got confused. Try deleting all the releases and tags (see https://github.com/attobot/attobot#updatingdeleting-a-release), and recreate it.

**Comment by ayush1999** [comment]
@simonbyrne Ok, I tried deleting and releases and starting afresh, but again attobot didn't create a PR. Not sure what's happening here.

**Comment by ayush1999** [comment]
Oh, attobot just made the PR. Not sure why it didn't work the first time.
