### ISSUE TITLE
using attobot on someone else's repository

### ISSUE THREAD

**Issue by gdkrmr** [attobot/attobot#60]
- What access rights do I need to a Github repository to activate attobot for it? I have just taken over maintainership of a package but I cannot add it to my attobot. I think that the owner simply added me to the list of collaborators. 
- What if I simply continue development on my fork, can I add my fork to the official julia package list instead of the original Github repo? What is the recommended way?

**Comment by gdkrmr** [comment]
never mind, it seemed you already had attobot installed.

**Comment by simonbyrne** [comment]
> * What access rights do I need to a Github repository to activate attobot for it? I have just taken over maintainership of a package but I cannot add it to my attobot. I think that the owner simply added me to the list of collaborators.

I think you need to be an owner/administrator to enable apps like AttoBot.

> * What if I simply continue development on my fork, can I add my fork to the official julia package list instead of the original Github repo? What is the recommended way?

AttoBot will only open PRs if the URL of the repo matches what is recorded in METADATA.

**Comment by gdkrmr** [comment]
Thanks for the info!
