### ISSUE TITLE
Error tagging new release switching to new package manager

### ISSUE THREAD

**Issue by felipenoris** [attobot/attobot#62]
See https://github.com/felipenoris/XLSX.jl/issues/96 and https://github.com/felipenoris/JSONWebTokens.jl/issues/11

Both releases are not compatible with pre-v1.0 versions, and I also removed the REQUIRE file from these repos. So I think attobot should do nothing on these cases, instead of openning an issue.

**Comment by simonbyrne** [comment]
The easier option is probably to disable attobot on the repository

**Comment by felipenoris** [comment]
Yes, I thought about that, but it looks like the "configure" button is gone.

**Comment by felipenoris** [comment]
Oh, I just found it. I had to go to my profile settings -> Applications -> Uninstall.

**Comment by simonbyrne** [comment]
on second thoughts, i can see this getting very annoying. I'll see if I can change it.
