### ISSUE TITLE
Attobot misprints closing backticks for REQUIRE diff if user left out final newline in REQUIRE file

### ISSUE THREAD

**Issue by KristofferC** [attobot/attobot#9]
As can be seen here https://github.com/JuliaLang/METADATA.jl/pull/7391 the formatting for the REQUIRE diff is not completely correct. The problem is that I didn't leave a newline at the end of my REQUIRE file so the closing triple backticks happen on the same line as the last REQUIRE entry.

**Comment by ararslan** [comment]
I'm working on a fix for this, PR incoming in a bit...
